/**
 * Golden test fixtures for the Rheem serial number decoder.
 */

import type { DecoderTestCase } from '../../../types';

export const RHEEM_VERIFIED_FIXTURES: readonly DecoderTestCase[] = [
  // 1. No-prefix serial: W291013412
  {
    description: 'No-prefix serial: W291013412 → Week 29, 2010',
    manufacturerId: 'rheem',
    serialNumber: 'W291013412',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 2010,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown', // 10-char collision triggers unknown
    source: null,
    notes: 'Week 29, 2010',
  },
  // 2. No-prefix serial: F0110999991234
  {
    description: 'No-prefix serial: F0110999991234 → Week 01, 2010',
    manufacturerId: 'rheem',
    serialNumber: 'F0110999991234',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 2010,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Week 01, 2010',
  },
  // 3. Numeric prefix: 6004M15989999
  {
    description: 'Numeric prefix: 6004M15989999 → Week 15, 1998',
    manufacturerId: 'rheem',
    serialNumber: '6004M15989999',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 1998,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Week 15, 1998',
  },
  // 4. Alphabetic prefix: TM07010000112345
  {
    description: 'Alphabetic prefix: TM07010000112345 → Week 07, 2001',
    manufacturerId: 'rheem',
    serialNumber: 'TM07010000112345',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 2001,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Week 07, 2001. Prefix is T. Plant is M.',
  },
  // 5. Long mixed prefix: CB5D302F099903346
  {
    description: 'Long mixed prefix: CB5D302F099903346 → Week 09, 1999',
    manufacturerId: 'rheem',
    serialNumber: 'CB5D302F099903346',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 1999,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Week 09, 1999',
  },
  // 6. Decoy-letter prefix: AB7E203M129703576
  {
    description: 'Decoy-letter prefix: AB7E203M129703576 → Week 12, 1997',
    manufacturerId: 'rheem',
    serialNumber: 'AB7E203M129703576',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 1997,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Week 12, 1997',
  },
  // 7. Greenville example: 8231G030417845
  {
    description: 'Greenville example: 8231G030417845 → Week 03, 2004',
    manufacturerId: 'rheem',
    serialNumber: '8231G030417845',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 2004,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Week 03, 2004',
  },
  // 8. Week 53 structural acceptance test
  {
    description: 'Week 53 structural acceptance test',
    manufacturerId: 'rheem',
    serialNumber: 'W531013412',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 2010,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Week 53 should decode correctly.',
  },
  // 13. Serial with spaces: 8231 G0304 17845
  {
    description: 'Serial with spaces: 8231 G0304 17845 → Week 03, 2004',
    manufacturerId: 'rheem',
    serialNumber: '8231 G0304 17845',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 2004,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Spaces should be normalized out.',
  },
  // 14. Unknown alphabetic plant candidate: Z0110999991234
  {
    description: 'Unknown alphabetic plant candidate (Z): Z0110999991234 → Week 01, 2010',
    manufacturerId: 'rheem',
    serialNumber: 'Z0110999991234',
    expectedStatus: 'success',
    expectedFormatId: 'rheem-modern-structural',
    expectedYear: 2010,
    expectedMonth: null,
    expectedConfidence: 'high',
    expectedProductType: 'unknown',
    source: null,
    notes: 'Plant Z is valid structurally.',
  },
] as const;

export const RHEEM_INVALID_FIXTURES: readonly DecoderTestCase[] = [
  // 9. Week 00 rejection
  {
    description: 'Week 00 rejection',
    manufacturerId: 'rheem',
    serialNumber: 'CB5D302F009903346',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedMonth: null,
    expectedConfidence: null,
    expectedProductType: null,
    source: null,
    notes: 'Week 00 is below range.',
  },
  // 10. Week 54 rejection
  {
    description: 'Week 54 rejection',
    manufacturerId: 'rheem',
    serialNumber: 'CB5D302F549903346',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedMonth: null,
    expectedConfidence: null,
    expectedProductType: null,
    source: null,
    notes: 'Week 54 is above range.',
  },
  // 11. All-numeric serial: 168252873
  {
    description: 'All-numeric serial: 168252873 → Unsupported',
    manufacturerId: 'rheem',
    serialNumber: '168252873',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedMonth: null,
    expectedConfidence: null,
    expectedProductType: null,
    source: null,
    notes: 'No alphabetic plant code anchor.',
  },
  // 16. Letters inside the terminal sequence
  {
    description: 'Letters inside the terminal sequence: M1210123A45',
    manufacturerId: 'rheem',
    serialNumber: 'M1210123A45',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedMonth: null,
    expectedConfidence: null,
    expectedProductType: null,
    source: null,
    notes: 'A45 is not a valid 4-digit numeric sequence. Sequence must be purely numeric.',
  },
] as const;
