import type { DecoderTestCase } from '../../../types';

export const fixtures: readonly DecoderTestCase[] = [
  // -------------------------------------------------------------------------
  // MODERN ICP UNITARY FORMAT (Format A)
  // -------------------------------------------------------------------------
  {
    manufacturerId: 'heil',
    serialNumber: 'E072514528',
    expectedStatus: 'success',
    expectedFormatId: 'heil-modern-unitary',
    expectedYear: 2007,
    expectedWeek: 25,
    expectedMonth: null,
    expectedProductType: 'unknown',
    expectedConfidence: 'high',
    source: null,
    description: 'H-MOD-01: Modern Format A - Known Field Example',
    notes: '2007, Week 25. Plant E.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: 'F211249697',
    expectedStatus: 'success',
    expectedFormatId: 'heil-modern-unitary',
    expectedYear: 2021,
    expectedWeek: 12,
    expectedMonth: null,
    expectedProductType: 'unknown',
    expectedConfidence: 'high',
    source: null,
    description: 'H-MOD-02: Modern Format A - TIC2021-0009 Documented Example',
    notes: '2021, Week 12. Plant F. Very high confidence source.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: 'L985212345',
    expectedStatus: 'success',
    expectedFormatId: 'heil-modern-unitary',
    expectedYear: 1998,
    expectedWeek: 52,
    expectedMonth: null,
    expectedProductType: 'unknown',
    expectedConfidence: 'high',
    source: null,
    description: 'H-MOD-03: Modern Format A - 1990s Boundary',
    notes: '1998, Week 52. Resolves to 1990s due to YY > 50 sliding window logic.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: 'L985412345',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedWeek: null,
    expectedMonth: null,
    expectedProductType: null,
    expectedConfidence: null,
    source: null,
    description: 'H-MOD-INV-01: Modern Format A - Invalid Week > 53',
    notes: 'Format theoretically matches length, but week 54 should fail or structural match should fail.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: 'L050012345',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedWeek: null,
    expectedMonth: null,
    expectedProductType: null,
    expectedConfidence: null,
    source: null,
    description: 'H-MOD-INV-02: Modern Format A - Invalid Week 00',
    notes: 'Week 00 is invalid.',
  },

  // -------------------------------------------------------------------------
  // HEIL-QUAKER DECADE FORMAT (Format B)
  // -------------------------------------------------------------------------
  {
    manufacturerId: 'heil',
    serialNumber: 'H55116328',
    expectedStatus: 'success',
    expectedFormatId: 'heil-quaker-decade',
    expectedYear: 1985,
    expectedWeek: 51,
    expectedMonth: null,
    expectedProductType: 'unknown',
    expectedConfidence: 'high',
    source: null,
    description: 'H-HQ-01: Legacy Format B - Known 1980s Example',
    notes: 'H = 1980s, 5 = +5 (1985), 51 = Week 51.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: 'G21412345',
    expectedStatus: 'success',
    expectedFormatId: 'heil-quaker-decade',
    expectedYear: 1972,
    expectedWeek: 14,
    expectedMonth: null,
    expectedProductType: 'unknown',
    expectedConfidence: 'high',
    source: null,
    description: 'H-HQ-02: Legacy Format B - 1970s Synthetic Example',
    notes: 'G = 1970s, 2 = +2 (1972), 14 = Week 14.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: 'Z55116328',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedWeek: null,
    expectedMonth: null,
    expectedProductType: null,
    expectedConfidence: null,
    source: null,
    description: 'H-HQ-INV-01: Legacy Format B - Invalid Decade Letter',
    notes: 'Z is not a valid decade letter for the 9-character format.',
  },

  // -------------------------------------------------------------------------
  // ICP DUCTLESS FORMATS (Format C)
  // -------------------------------------------------------------------------
  {
    manufacturerId: 'heil',
    serialNumber: 'V2028V10001',
    expectedStatus: 'success',
    expectedFormatId: 'heil-ductless-modern',
    expectedYear: 2020,
    expectedWeek: 28,
    expectedMonth: null,
    expectedProductType: 'unknown',
    expectedConfidence: 'high',
    source: null,
    description: 'H-DUC-01: Ductless Newer Format - Documented Example',
    notes: 'V prefix, 20 = 2020, 28 = Week 28, V separator.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: '1419V10001',
    expectedStatus: 'success',
    expectedFormatId: 'heil-ductless-legacy',
    expectedYear: 2014,
    expectedWeek: 19,
    expectedMonth: null,
    expectedProductType: 'unknown',
    expectedConfidence: 'high',
    source: null,
    description: 'H-DUC-02: Ductless Older Format - Synthetic Example',
    notes: '14 = 2014, 19 = Week 19, V separator.',
  },

  // -------------------------------------------------------------------------
  // UNSUPPORTED / EXPLICIT REJECTION
  // -------------------------------------------------------------------------
  {
    manufacturerId: 'heil',
    serialNumber: '297448',
    expectedStatus: 'insufficient-info',
    expectedFormatId: null,
    expectedYear: null,
    expectedWeek: null,
    expectedMonth: null,
    expectedProductType: null,
    expectedConfidence: null,
    source: null,
    description: 'H-UNS-01: Legacy 6-Digit Numeric',
    notes: 'Explicitly unsupported. Must return insufficient-info error.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: 'HFF120465',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedWeek: null,
    expectedMonth: null,
    expectedProductType: null,
    expectedConfidence: null,
    source: null,
    description: 'H-UNS-02: HFF alleged recall format',
    notes: 'Explicitly unsupported. Should fail to match any valid date rules.',
  },
  {
    manufacturerId: 'heil',
    serialNumber: 'N8MSL0451412A',
    expectedStatus: 'unsupported',
    expectedFormatId: null,
    expectedYear: null,
    expectedWeek: null,
    expectedMonth: null,
    expectedProductType: null,
    expectedConfidence: null,
    source: null,
    description: 'H-UNS-03: Model number acting as serial',
    notes: 'Too long. Should fail.',
  },
];
